apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfbuddy-server
  annotations:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: tfbuddy-server
    app.kubernetes.io/part-of: tfbuddy
  labels:
    app.kubernetes.io/name: tfbuddy-server
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tfbuddy-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: tfbuddy-server
        app.kubernetes.io/part-of: tfbuddy
      labels:
        app.kubernetes.io/name: tfbuddy-server
    spec:
      containers:
        - name: tfbuddy-server
          env:
          - name: PORT
            value: "8080"
          - name: TFBUDDY_LOG_LEVEL
            value: "debug"
          - name: TFBUDDY_NATS_SERVICE_URL
            value: nats://tfbuddy-nats:4222
          - name: TFBUDDY_OTEL_ENABLED
            value: "false"
          - name: TFBUDDY_OTEL_COLLECTOR_PORT
            value: "4317"
          - name: TFBUDDY_OTEL_COLLECTOR_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          image: ghcr.io/zapier/tfbuddy:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: tfbuddy
      terminationGracePeriodSeconds: 30

