apiVersion: batch/v1
kind: Job
metadata:
  name: wait-ngrok-url
spec:
  template:
    spec:
      containers:
        - name: curl
          image: registry.gitlab.com/gitlab-ci-utils/curl-jq:latest
          command: [
            "/bin/bash", "-c",
            "curl http://ngrok:4040/api/tunnels | jq --raw-output '.tunnels[0].public_url' | grep ngrok"
          ]
      restartPolicy: OnFailure
  backoffLimit: 10
